![posPUC.png]()
# **Pós-graduação Engenharia de Software**
# **Introdução à Programação com Python**
# Aula 01 - Resolução dos Exercícios

por **Luciana SA Amancio**

# Lista 01 - Operadores Aritméticos e Expressões

In [1]:
# Soma (+)
13+5

18

In [3]:
# Subtração (-)
13-5

8

In [6]:
# Multiplicação (*)
13*5

65

In [8]:
# Exponenciação (**)
13**5

371293

In [9]:
# Divisão (/)
13/5

2.6

In [13]:
# Divisão Inteira (//)
13//5

2

In [14]:
# Resto da Divisão (%)
13-(13//5)*5

3

**DESAFIO 1**

Qual o volume, em metros cúbicos, de um reservatório, em forma de paralelepípedo, com 79 metros de comprimento, 10 metros de largura e 4 metros de profundidade?

**DESAFIO 1**

Qual o volume, em metros cúbicos, de um reservatório, em forma de paralelepípedo, com 79 metros de comprimento, 10 metros de largura e 4 metros de profundidade?

In [28]:
# V = C x L x h, onde V é o volume, C é o comprimento, L é a largura e h é a altura.
79*10*4

3160

**DESAFIO 2**

Considerando que 1 metro cúbico corresponde a 1000 litros de água, quantos litros cabem no reservatório do desafio 1?

In [29]:
# Nesse caso se quer em litros é só multiplicar por 1000
79*10*4*1000

3160000

**DESAFIO 3**

Considere uma torneira que despeja 75 litros de água por hora. Em quantos minutos a torneira encheria o reservatório dos desafios 1 e 2?

In [30]:
# Aplicada a regra de três simples:
# água (em L)     Tempo (em minutos)
#   75              60
# 79*10*4*1000      x
79*10*4*1000*60/75

2528000.0

# Lista 02 - Variáveis

**DESAFIO 1**

Considere uma torneira que despeja 75 litros de água por hora. Em quantos minutos a torneira encheria o reservatório dos desafios 1 e 2?

In [31]:
# Aplicada a regra de três simples:
# água (em L)     Tempo (em minutos)
#   75              60
# 79*10*4*1000      x
vazaoPorMinuto = 75/60
79*10*4*1000/vazaoPorMinuto

2528000.0

**DESAFIO 2**

A fórmula de Bhaskara abaixo calcula as duas raízes reais de uma equação do 2º grau, uma utilizando o sinal '+' e a outra, o sinal '-'. Calcule as raízes para os coeficientes: a = 1, b = 5 e c = 6. Dica: um valor elevado ao expoente 0.5 é equivalente à raiz quadrada do valor.

![posPUC.png]()

In [39]:
# Cálculos e exibição da 1a. raiz (x1)
a = 1
b = 5
c = 6
raizDelta = (b ** 2 - 4 * a * c) ** 0.5
x1 = (-b + raizDelta) / (2 * a)
x1

-2.0

In [40]:
# Cálculos e exibição da 2a. raiz (x2)
a = 1
b = 5
c = 6
raizDelta = (b ** 2 - 4 * a * c) ** 0.5
x2 = (-b - raizDelta) / (2 * a)
x2

-3.0

Outra solução possível utilizando Python:

In [41]:
# Cálculos e exibição da 1a. raiz (x1)
a = 1
b = 5
c = 6
raizDelta = (b ** 2 - 4 * a * c) ** 0.5
x1 = (-b + raizDelta) / (2 * a)
x2 = (-b - raizDelta) / (2 * a)
x1

-2.0

In [43]:
# Exibição da 2a. raiz (x2) o cálculo já feito no código acima.
x2

-3.0

# Lista 03 - Strings e Listas

**DESAFIO 1**

Crie uma variável com o seu nome e exiba a quantidade de caracteres armazenados na variável.

In [60]:
nome = 'Luciana da Silva Abreu Amancio'
# A função len retorna a quantidade de caracteres de uma string.
len(nome)

30

**DESAFIO 2**

Crie uma variável com uma string representando a data de seu nascimento no formato 'dd/mm/aaaa'. Em seguida, crie e exiba uma senha composta pela concatenção das partes definidas abaixo, na ordem apresentada:
*   o último caractere do ano;
*   1o. caractere do mês replicado 5 vezes;
*   2o. caractere do dia;
*   2o. caractere do ano replicado 2 vezes.

In [61]:
dataNascimento = '09/07/1984'
senha = dataNascimento[-1] + dataNascimento[3] * 5 + dataNascimento[1] + dataNascimento[-3] * 2
senha

'400000999'

Gabarito do Desafio 2:

In [62]:
data = '18/03/1921'
data[-1] + data[3] * 5 + data[1] + data[-3] * 2

'100000899'

**DESAFIO 3**

Agora vamos criar uma senha mais forte! Crie uma variável com uma string representando a data de seu nascimento no formato 'dd/mm/aaaa'. Crie outra variável com o seu nome. Em seguida, crie e exiba uma senha composta pela concatenção das partes definidas abaixo, na ordem apresentada:
*   o penúltimo caractere do ano;
*   o caractere '#';
*   o caractere do meio do nome;
*   o 2o. caractere do mês replicada 3 vezes;
*   o caractere '$';
*   o antepenúltimo caractere do nome replicado 2 vezes.

In [63]:
dataNascimento = '09/07/1984'
nome = "Luciana SA Amancio"
# Lembre-se que índices devem ser inteiros; por isso, //
senhaForte = dataNascimento[-2] + '#' + nome[len(nome)//2] + dataNascimento[3] * 2 + '$' + nome[-3] * 2
senhaForte

'8#A00$cc'

Gabarito do Desafio 3:

In [64]:
data = '18/03/1921'
nome = 'Pato Donald'
# Lembre-se que índices devem ser inteiros; por isso, //
data[-2] + '#' + nome[len(nome) // 2] + 3 * data[4] + '$' + nome[-3] * 2

'2#D333$aa'

**DESAFIO 4**

Crie uma variável string com todas as letras maiúsculas do alfabeto, de 'A' a 'Z'. Em seguida, crie uma variável lista com os valores inteiros 15, 24, 19, 7, 14 e 13. Considerando que cada inteiro da lista corresponde ao índice da posição de uma letra na string, exiba a concatenação de todas as 6 letras e descubra a "palavra secreta". Por exemplo, se a lista possuir os valores 14 e 0, a palavra secreta será 'OI'.

In [65]:
alfabetoMaiusculo = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
listaInteiros = [15, 24, 19, 7, 14, 13]
palavraSecreta = alfabetoMaiusculo[listaInteiros[0]] + alfabetoMaiusculo[listaInteiros[1]] + alfabetoMaiusculo[listaInteiros[2]] + alfabetoMaiusculo[listaInteiros[3]] + alfabetoMaiusculo[listaInteiros[4]] + alfabetoMaiusculo[listaInteiros[5]]
palavraSecreta

'PYTHON'

Gabarito do Desafio 4:

In [66]:
s = 'ABCDEFGHIJKLMNOPQRSTUVXWYZ'
l = [15, 24, 19, 7, 14, 13]
s[l[0]] + s[l[1]] + s[l[2]] + s[l[3]] + s[l[4]] + s[l[5]]

'PYTHON'

# Lista 04 - Conversão de tipos e módulos

**DESAFIO 1**

Utilizando uma constante do módulo string, refaça o desafio 4 da lista anterior, reproduzido abaixo.

Crie uma variável string com todas as letras maiúsculas do alfabeto. Em seguida, crie uma variável lista com os valores inteiros 15, 24, 19, 7, 14 e 13. Considerando que cada inteiro da lista corresponde ao índice da posição de uma letra na string, exiba a concatenação de todas as 6 letras e descubra a "palavra secreta". Por exemplo, se a lista possuir os valores 14 e 0, a palavra secreta será 'OI'.

In [69]:
# Importando o módulo string que disponibiliza um conjunto de constantes strings, como letras maiúsculas, minúsculas e sinais de pontuação.
import string as stringAlfabeto
stringAlfabeto = stringAlfabeto.ascii_uppercase
listaInteiros = [15, 24, 19, 7, 14, 13]
palavraSecreta = alfabetoMaiusculo[listaInteiros[0]] + alfabetoMaiusculo[listaInteiros[1]] + alfabetoMaiusculo[listaInteiros[2]] + alfabetoMaiusculo[listaInteiros[3]] + alfabetoMaiusculo[listaInteiros[4]] + alfabetoMaiusculo[listaInteiros[5]]
palavraSecreta

'PYTHON'

Gabarito do Desafio 1:

In [68]:
import string as st
s = st.ascii_uppercase
l = [15, 24, 19, 7, 14, 13]
s[l[0]] + s[l[1]] + s[l[2]] + s[l[3]] + s[l[4]] + s[l[5]]

'PYTHON'

**DESAFIO 2**

Utilizando a função log10 do módulo math, calcule o log do valor 10000 na base 10.

In [70]:
# Importando o Módulo math: constantes e funções matemáticas
import math
math.log(10000, 10)

4.0

**DESAFIO 3**

Considere uma string composta por 4 algarismos como, por exemplo, '1234'. Exiba a soma dos algarismos da string exemplo. Importante: a sua solução deve funcionar para qualquer string composta por 4 algarismos. Por isso, depois de executar a sua solução, substitua a string '1234' por '8751' e execute-a novamente.

In [71]:
s = '1234'
int(s[0]) + int(s[1]) + int(s[2]) + int(s[3])

10

In [72]:
s = '8751'
int(s[0]) + int(s[1]) + int(s[2]) + int(s[3])

21

In [73]:
# Desafio 3 - outra solução
s = '8751'
n = int(s)
n1 = n // 1000              # dígito da unidade de milhar
n2 = n // 10 // 10 % 10     # dígito da centena
n3 = n // 10 % 10           # dígito da dezena
n4 = n % 10                 # dígito da unidade
n1 + n2 + n3 + n4

21

# Lista 05 - Função Print

**DESAFIO 1**

Escreva um programa que exiba o correspondente a 23 dias em semanas e dias. Exiba uma mensagem adequada usando as palavras 'semanas' e 'dias' após as respectivas quantidades.

Importante: a sua solução deve funcionar para qualquer quantidade de dias. Por isso, depois de executar a sua solução para 23 dias, execute-a novamente para 144 dias.

In [1]:
dias = 23
semanas = dias // 7
dias = dias % 7
print(f'{semanas} semanas e {dias} dias')

3 semanas e 2 dias

In [2]:
dias = 144
semanas = dias // 7
dias = dias % 7
print(f'{semanas} semanas e {dias} dias')

20 semanas e 4 dias

**DESAFIO 2**

A cada execução, a função random do módulo de mesmo nome gera um valor real aletaório no intervalo [0, 1), ou seja, maior ou igual a 0 e menor do que 1. Escreva um programa que gere um valor aleatório com essa função e exiba-o de diferentes formas:

* sem detalhes de formatação, sem utilizar uma f-string;
* sem detalhes de formatação, utilizando uma f-string;
* com 4 casas decimais;
* com 4 casas em um campo de tamanho 7;
* com 6 casas decimais em um campo de tamanho 12 e com zeros à frente.

In [3]:
from random import random
n = random()
print(n)
print(f'{n}')
print(f'{n:.4f}')
print(f'{n:7.4f}')
print(f'{n:012.6f}')

0.7085939447467497
0.7085939447467497
0.7086
 0.7086
00000.708594

# Lista 06

**DESAFIO 1**

Escreva um programa que leia um valor inteiro representando uma quantidade de dias e exiba-o convertido em semanas e dias. Por exemplo, se o usuário digitar 23, o programa deverá exibir a mensagem:

3 semanas e 2 dias

Dica: utilize os operadores // e %.

Importante: execute a sua solução mais de uma vez, digitando valores diferentes e observe os resultados.

In [4]:
dias = 23
semanas = dias // 7
dias = dias % 7
print(f'{semanas} semanas e {dias} dias')

3 semanas e 2 dias

In [5]:
dias = 144
semanas = dias // 7
dias = dias % 7
print(f'{semanas} semanas e {dias} dias')

20 semanas e 4 dias

**DESAFIO 2**

Escreva um programa que leia três inteiros representando horas, minutos e segundos e imprima o total em segundos. Por exemplo, se forem lidos os valores 2, 5 e 78, o programa deverá exibir:

7578 segundos

In [6]:
horas = int(input('Digite o total de horas: '))
minutos = int(input('Digite o total de minutos: '))
segundos = int(input('Digite o total de segundos: '))
total = horas * 3600 + minutos * 60 + segundos
print(f'Total de segundos: {total}')

Digite o total de horas: 1
Digite o total de minutos: 10
Digite o total de segundos: 5
Total de segundos: 4205

**DESAFIO 3**

Escreva um programa que leia um inteiro representando um valor em segundos e o imprima no formato horas:minutos:segundos. Por exemplo, se for lido o valor 8752, o programa deverá exibir a mensagem:

2:25:52

In [7]:
segundos = int(input('Digite o total de segundos: '))
horas = segundos // 3600
minutos = segundos % 3600 // 60
segundos = segundos % 3600 % 60
print(f'{horas}:{minutos}:{segundos}')

Digite o total de segundos: 4205
1:10:5

**DESAFIO 4**

Imagine um caixa eletrônico de um banco qualquer e considere notas nos seguintes valores em reais: 100, 50, 20, 10, 5, 2 e 1.

Escreva um programa para esse caixa eletrônico que leia um número inteiro representando um valor em reais e exiba a menor quantidade de notas para se obter o montante fornecido. Deverá ser exibida a quantidade de cada nota existente. Por exemplo, se for lido o valor 371, o programa deverá exibir a mensagem:

Notas de R$ 100: 3

Notas de R$ 50: 1

Notas de R$ 20: 1

Notas de R$ 10: 0

Notas de R$ 5: 0

Notas de R$ 2: 0

Notas de R$ 1: 1

In [17]:
# Leitura do valor em reais
valor = int(input('Digite o valor do saque: '))

# Cálculo das quantidades de notas por valor
n100 = valor // 100
resto = valor % 100
n50 = resto // 50
resto = resto % 50
n20 = resto // 20
resto = resto % 20
n10 = resto // 10
resto = resto % 10
n5 = resto // 5
resto = resto % 5
n2 = resto // 2
n1 = resto % 2

# Exibição dos resultados
print(f'Notas de R$ 100: {n100}')
print(f'Notas de R$ 50: {n50}')
print(f'Notas de R$ 20: {n20}')
print(f'Notas de R$ 10: {n10}')
print(f'Notas de R$ 5: {n5}')
print(f'Notas de R$ 2: {n2}')
print(f'Notas de R$ 1: {n1}')

Digite o valor do saque: 20588
Notas de R$ 100: 205
Notas de R$ 50: 1
Notas de R$ 20: 1
Notas de R$ 10: 1
Notas de R$ 5: 1
Notas de R$ 2: 1
Notas de R$ 1: 1

**DESAFIO 5**

Uma universidade, fundada em 2010, representa a matrícula de um aluno via um número inteiro com 6 algarismos no formato AASNNN, onde:

* os dois primeiros algarismos, representados por AA, são os dois últimos algarismos do ano de ingresso; 24, por exemplo, seria relativo ao ano 2024;

* o terceiro algarismo, representado por S, vale 1 ou 2, conforme o aluno tenha ingressado no 1º ou no 2º semestre;

* os três últimos dígitos, representados por NNN, correspondem à colocação do
aluno no vestibular de ingresso na universidade.

Por exemplo, a matrícula 171069 indica que o aluno ingressou em no 1º período de 2017 e ficou em 69º lugar no vestibular.

Escreva um programa que leia o nome e a matrícula de um aluno e exiba o ano e o semestre em que ele ingressou nessa universidade e sua colocação no vestibular.

In [18]:
nome = input('Digite o nome do aluno: ')
matricula = int(input('Digite a matrícula do aluno: '))
ano = 2000 + matricula // 10000
semAno = matricula % 10000
semestre = semAno // 1000
colocacao = semAno % 1000
print(f'Nome: {nome}\nAno: {ano}\nSemestre: {semestre}\nColocação: {colocacao}')

Digite o nome do aluno: Luciana
Digite a matrícula do aluno: 25896
Nome: Luciana
Ano: 2002
Semestre: 5
Colocação: 896